logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring:
  jpa:
    show-sql: true
    properties.format_sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
        hibernate:
          ########## mysql ##########
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          ########## h2 ##########
          #   dialect: org.hibernate.dialect.H2Dialect

  datasource:
    ########## mysql db ##########
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/megamart
    username: megamart
    password: megamart
    ########## h2 db ##########
    #      driverClassName: org.h2.Driver
    #      url: jdbc:h2:mem:myDb
    #      username: sa
    #      password:
    #      h2:
    #        console:
    #          enabled: true
    #          path: /h2

server.port: 8010